# Generated by Django 4.0.2 on 2022-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='singatures'),
        ),
    ]
