# Generated by Django 4.0.2 on 2022-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures'),
        ),
    ]
