# Generated by Django 4.0.2 on 2022-04-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
