# Generated by Django 4.0.2 on 2022-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_items', '0002_routeitem_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeitem',
            name='action_type',
            field=models.CharField(choices=[('VIEW', 'view'), ('SIGN', 'sign'), ('OTHER', 'other')], default='VIEW', max_length=8),
        ),
    ]
