# Generated by Django 4.0.2 on 2022-04-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_file_route_item'),
        ('route_items', '0003_alter_routeitem_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
