# Generated by Django 4.0.2 on 2022-05-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_slips', '0011_remove_routeslip_shared_with'),
        ('route_items', '0007_remove_routeitem_form_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeitem',
            name='route_slip_id',
        ),
        migrations.AddField(
            model_name='routeitem',
            name='route_slip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route_slips.routeslip'),
        ),
    ]
