# Generated by Django 4.0.2 on 2022-03-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0003_rename_user_folder_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('order_type', models.CharField(choices=[('in_order', 'In Order'), ('parallel', 'Parallel'), ('both', 'Both')], max_length=16, null=True)),
                ('current_id', models.IntegerField()),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder')),
            ],
        ),
    ]
