# Generated by Django 4.0.2 on 2022-03-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_slips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeslip',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routeslip',
            name='current_id',
            field=models.IntegerField(null=True),
        ),
    ]
