# Generated by Django 4.0.2 on 2022-03-27 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_folder_current_active_route'),
        ('route_slips', '0003_routeslip_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeslip',
            old_name='current_id',
            new_name='current_route_item_id',
        ),
        migrations.AddField(
            model_name='routeslip',
            name='shared_with',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='routeslip',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='routeslip',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routeSlips', to='folders.folder'),
        ),
    ]
