# Generated by Django 4.0.2 on 2022-04-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_slips', '0004_rename_current_id_routeslip_current_route_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeslip',
            name='route_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
