# Generated by Django 4.0.2 on 2022-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_slips', '0005_routeslip_route_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeslip',
            name='order_type',
            field=models.CharField(blank=True, choices=[('IN_ORDER', 'inorder'), ('PARALLEL', 'parallel'), ('BOTH', 'both')], default='IN_ORDER', max_length=16),
        ),
    ]
