# Generated by Django 4.0.2 on 2022-05-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_slips', '0008_routeslip_route_items_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeslip',
            name='slug',
        ),
        migrations.AlterField(
            model_name='routeslip',
            name='order_type',
            field=models.CharField(choices=[('IN_ORDER', 'inorder'), ('PARALLEL', 'parallel'), ('BOTH', 'both')], default='IN_ORDER', max_length=16),
        ),
        migrations.AlterField(
            model_name='routeslip',
            name='route_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
