# Generated by Django 4.0.2 on 2022-05-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_alter_folder_desired_completion_date'),
        ('route_slips', '0009_remove_routeslip_slug_alter_routeslip_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeslip',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
    ]
