# Generated by Django 4.0.2 on 2022-05-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_slips', '0010_alter_routeslip_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeslip',
            name='shared_with',
        ),
    ]
