# Generated by Django 4.0 on 2022-02-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('folder', 'name')},
        ),
    ]
