# Generated by Django 4.0 on 2022-02-08 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_alter_folder_unique_together'),
        ('users', '0002_alter_user_managers'),
        ('files', '0002_file_folder_alter_file_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='folder',
            new_name='parent_folder',
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('parent_folder', 'name')},
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
