# Generated by Django 4.0 on 2022-02-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_folder_file_parent_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
