# Generated by Django 4.0.2 on 2022-04-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_items', '0003_alter_routeitem_action_type'),
        ('files', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='route_item',
            field=models.ForeignKey(default='8e79e5a4-cbf2-4d26-89fb-3160e2e6adfc', on_delete=django.db.models.deletion.CASCADE, to='route_items.routeitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
