# Generated by Django 4.0.2 on 2022-04-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_route_item_alter_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='route_item',
        ),
    ]
