# Generated by Django 4.0 on 2022-02-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'name')},
        ),
    ]
