# Generated by Django 4.0 on 2022-02-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
        ('folders', '0002_alter_folder_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name')},
        ),
    ]
