# Generated by Django 4.0.2 on 2022-03-04 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_rename_user_folder_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='desired_completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='expedited',
            field=models.BooleanField(default=False),
        ),
    ]
