# Generated by Django 4.0.2 on 2022-05-06 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_folder_current_active_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='desired_completion_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
