# Generated by Django 4.0.2 on 2022-05-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_alter_folder_desired_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(default='ffffff', max_length=16),
        ),
    ]
