# Generated by Django 4.0.2 on 2022-05-09 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motleycrew_messages', '0002_rename_seen_message_read_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(null=True),
        ),
    ]
