# Generated by Django 4.0.2 on 2022-05-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_file_route_item'),
        ('motleycrew_messages', '0003_alter_message_created_at_alter_message_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ForeignKey(default=83, on_delete=django.db.models.deletion.DO_NOTHING, to='files.file'),
            preserve_default=False,
        ),
    ]
