# Generated by Django 4.0.2 on 2022-05-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_items', '0007_remove_routeitem_form_field'),
        ('motleycrew_messages', '0004_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='route_item',
            field=models.ForeignKey(default='bcedd11f-48ab-4a55-88b4-12b807b81a9e', on_delete=django.db.models.deletion.DO_NOTHING, to='route_items.routeitem'),
            preserve_default=False,
        ),
    ]
