# Generated by Django 4.0.2 on 2022-05-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motleycrew_messages', '0005_message_route_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
