# Generated by Django 4.0.2 on 2022-05-07 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_items', '0007_remove_routeitem_form_field'),
        ('form_fields', '0003_remove_formfield_dimensions_formfield_form_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='route_item',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='route_items.routeitem'),
            preserve_default=False,
        ),
    ]
