# Generated by Django 4.0.2 on 2022-05-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_items', '0007_remove_routeitem_form_field'),
        ('form_fields', '0004_formfield_route_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='route_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_items.routeitem'),
        ),
    ]
