# Generated by Django 4.0.2 on 2022-05-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_fields', '0005_alter_formfield_route_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='refh',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='formfield',
            name='refw',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
